# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.box = 'debian/buster64'
  config.vm.network "private_network", ip: "172.27.11.10"
  config.vm.hostname = "lua.example.local"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "2"
  end
  config.vm.provider "libvirt" do |lv|
    lv.memory = "1024"
    lv.cpus = "2"
    lv.cputopology :sockets => '1', :cores => '1', :threads => '2'
  end
  config.vm.provision "shell", path: "provision.sh"

end
